name: Syntax Check

on:
  push:
    branches: [main]

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install pycodestyle
      run: pip install pycodestyle

    - name: Syntax check
      run: |
        # Polecenie do sprawdzenia zgodności z PEP 8
        pycodestyle .
